const GENRES=['Old','Rom Com','Drama','Comedy','Horror','Sci Fi','Western','Faith / Inspiration','Children','Documentary','Anime','Adventure','Crime','Fantasy','History','Music','Mystery','Thriller','War'];
const STREAMERS=['Netflix','Prime Video','Disney+','Apple TV','Angel','Max','Hulu','Peacock','Paramount+'];
const MME_V5_TOM_BEN=true;
let activeGenre='All';
const MOVIES=[
 {id:'dune-2',title:'Dune: Part Two',year:2024,months:4,genres:['Sci Fi','Adventure'],view:'sponsored',providers:['In theaters','Apple TV'],trailer:'https://www.youtube.com/results?search_query=Dune+Part+Two+trailer',c1:'#9a3412',c2:'#111827',synopsis:'A big-screen science-fiction spectacle. Availability: in theaters; rental later.'},
 {id:'inside-out-2',title:'Inside Out 2',year:2024,months:2,genres:['Children','Comedy'],view:'sponsored',providers:['In theaters','Disney+'],trailer:'https://www.youtube.com/results?search_query=Inside+Out+2+trailer',c1:'#d946ef',c2:'#0891b2',synopsis:'Family-friendly animated sequel. Availability: in theaters; Disney+ later.'},
 {id:'past-lives',title:'Past Lives',year:2023,months:12,genres:['Drama','Rom Com'],view:'ad-free',providers:['Netflix','Apple TV'],trailer:'https://www.youtube.com/results?search_query=Past+Lives+trailer',c1:'#0f766e',c2:'#1e293b',synopsis:'A quiet adult drama about memory, love, and the roads not taken.'},
 {id:'oppenheimer',title:'Oppenheimer',year:2023,months:11,genres:['Drama','History'],view:'vod',providers:['Prime Video','Apple TV'],trailer:'https://www.youtube.com/results?search_query=Oppenheimer+trailer',c1:'#7f1d1d',c2:'#111827',synopsis:'Prestige historical drama. Availability: streaming/rental providers.'},
 {id:'casablanca',title:'Casablanca',year:1942,months:999,genres:['Old','Rom Com'],view:'ad-free',providers:['Apple TV','Prime Video'],trailer:'https://www.youtube.com/results?search_query=Casablanca+trailer',c1:'#334155',c2:'#020617',synopsis:'Classic library discovery. Availability: rental or purchase platforms.'},
 {id:'the-holdovers',title:'The Holdovers',year:2023,months:9,genres:['Comedy','Drama'],view:'vod',providers:['Prime Video','Apple TV'],trailer:'https://www.youtube.com/results?search_query=The+Holdovers+trailer',c1:'#365314',c2:'#111827',synopsis:'Warm character-driven movie-night recommendation.'},
 {id:'barbie',title:'Barbie',year:2023,months:11,genres:['Comedy','Fantasy'],view:'sponsored',providers:['Max','Apple TV'],trailer:'https://www.youtube.com/results?search_query=Barbie+movie+trailer',c1:'#be185d',c2:'#f9a8d4',synopsis:'Popular comedy/fantasy with clear provider routing.'},
 {id:'the-godfather',title:'The Godfather',year:1972,months:999,genres:['Old','Crime','Drama'],view:'ad-free',providers:['Paramount+','Apple TV'],trailer:'https://www.youtube.com/results?search_query=The+Godfather+trailer',c1:'#111827',c2:'#450a0a',synopsis:'Classic crime drama saved as a title, not just a trailer.'},
 {id:'wicked',title:'Wicked',year:2024,months:1,genres:['Fantasy','Music'],view:'sponsored',providers:['In theaters'],trailer:'https://www.youtube.com/results?search_query=Wicked+movie+trailer',c1:'#166534',c2:'#581c87',synopsis:'First-run theater title. Availability: in theaters; use Tribute / Now Playing for times.'},
 {id:'angel-studios',title:'Sound of Hope',year:2024,months:3,genres:['Faith / Inspiration','Drama'],view:'all',providers:['Angel','In theaters'],trailer:'https://www.youtube.com/results?search_query=Sound+of+Hope+trailer',c1:'#1d4ed8',c2:'#0f172a',synopsis:'Faith/inspiration lane with theater and Angel-platform routing.'},
 {id:'civil-war',title:'Civil War',year:2024,months:5,genres:['Thriller','Drama'],view:'sponsored',providers:['In theaters','Apple TV'],trailer:'https://www.youtube.com/results?search_query=Civil+War+movie+trailer',c1:'#78350f',c2:'#0f172a',synopsis:'Current-release thriller. Theater availability is high level only.'},
 {id:'spirited-away',title:'Spirited Away',year:2001,months:999,genres:['Anime','Fantasy','Children'],view:'ad-free',providers:['Max','Apple TV'],trailer:'https://www.youtube.com/results?search_query=Spirited+Away+trailer',c1:'#0e7490',c2:'#312e81',synopsis:'Anime/family classic for saved-title library behavior.'}
];
const $=s=>document.querySelector(s); const $$=s=>[...document.querySelectorAll(s)];
const storeKey='mmeTomReviewProfile'; const profilesKey='mmeTomReviewProfiles'; const activeProfileKey='mmeTomReviewActiveProfile'; const libKey='mmeTomReviewLibrary';
let profiles=JSON.parse(localStorage.getItem(profilesKey)||'{}');
let activeProfileName=localStorage.getItem(activeProfileKey)||'';
let profile=activeProfileName&&profiles[activeProfileName]?profiles[activeProfileName]:JSON.parse(localStorage.getItem(storeKey)||'{}');
let library=new Set(JSON.parse(localStorage.getItem(libKey)||'[]'));
function save(){localStorage.setItem(storeKey,JSON.stringify(profile));localStorage.setItem(profilesKey,JSON.stringify(profiles));localStorage.setItem(activeProfileKey,activeProfileName||'');localStorage.setItem(libKey,JSON.stringify([...library]));}
function profileKeyFromForm(){return ($('#profileName')?.value.trim()||$('#userName')?.value.trim()||'Default profile')}
function refreshProfilePicker(){let picker=$('#profilePicker'); if(!picker)return; let names=Object.keys(profiles).sort((a,b)=>a.localeCompare(b)); picker.innerHTML='<option value="">New profile</option>'+names.map(n=>`<option value="${n.replace(/&/g,'&amp;').replace(/"/g,'&quot;')}">${n}</option>`).join(''); picker.value=activeProfileName&&profiles[activeProfileName]?activeProfileName:''}
function selectedGenres(){return [...$('#genreSelect').selectedOptions].map(o=>o.value)}
function selectedProviders(){if($('#platformAll').checked)return ['All'];return $$('.provider:checked').map(x=>x.value)}
function imdbUrl(m){return 'https://www.imdb.com/find/?q='+encodeURIComponent(m.title+' '+m.year)}
function setActiveGenre(g){activeGenre=g||'All';renderResults();renderV5Drawer();}
function genreChoices(){let selected=profile.genres&&profile.genres.length?profile.genres:GENRES;return ['All'].concat(selected.filter((g,i,a)=>a.indexOf(g)===i));}
function init(){GENRES.forEach(g=>{let o=document.createElement('option');o.value=o.textContent=g;$('#genreSelect').appendChild(o)});STREAMERS.forEach(s=>{let l=document.createElement('label');l.className='check';l.innerHTML=`<input class="provider" type="checkbox" value="${s}"> ${s}`;$('#streamers').appendChild(l)});refreshProfilePicker();applyProfileToForm();bind();render();}
function applyProfileToForm(){if(profile.userName)$('#userName').value=profile.userName;if($('#profileName'))$('#profileName').value=activeProfileName||profile.profileName||profile.userName||'';if(profile.genres){[...$('#genreSelect').options].forEach(o=>o.selected=profile.genres.includes(o.value))}if(profile.release)$$('input[name=release]').forEach(r=>r.checked=r.value===profile.release);if(profile.fromYear)$('#fromYear').value=profile.fromYear;if(profile.toYear)$('#toYear').value=profile.toYear;if(profile.view)$('#viewSelect').value=profile.view;if(profile.zip)$('#zipInput').value=profile.zip;if(profile.providers){$('#platformAll').checked=profile.providers.includes('All');$$('.provider').forEach(c=>c.checked=profile.providers.includes(c.value))}}
function bind(){if($('#profilePicker'))$('#profilePicker').onchange=()=>{let name=$('#profilePicker').value;if(name&&profiles[name]){activeProfileName=name;profile={...profiles[name]};applyProfileToForm();save();render();}};if($('#deleteProfile'))$('#deleteProfile').onclick=()=>{let name=$('#profilePicker')?.value||activeProfileName;if(name&&profiles[name]){delete profiles[name];activeProfileName='';profile={};save();refreshProfilePicker();applyProfileToForm();render();}};$('#profileForm').addEventListener('submit',e=>{e.preventDefault();profile.userName=$('#userName').value.trim()||'Guest';profile.profileName=profileKeyFromForm();profile.genres=selectedGenres();profile.release=$('input[name=release]:checked').value;profile.fromYear=$('#fromYear').value;profile.toYear=$('#toYear').value;profile.view=$('#viewSelect').value;profile.zip=$('#zipInput').value.trim();profile.providers=selectedProviders();activeProfileName=profile.profileName;profiles[activeProfileName]={...profile};save();refreshProfilePicker();render();location.hash='titles'});$('#savePlatforms').onclick=()=>{$('#profileForm').requestSubmit()};$('#platformAll').onchange=()=>{if($('#platformAll').checked)$$('.provider').forEach(c=>c.checked=false)};$$('.provider').forEach(c=>c.onchange=()=>{if(c.checked)$('#platformAll').checked=false});$('#demoProfile').onclick=()=>{profile={userName:'Tom',profileName:'Tom demo profile',genres:['Drama','Comedy','Old','Crime'],release:'any',view:'all',zip:'20001',providers:['All']};activeProfileName=profile.profileName;profiles[activeProfileName]={...profile};refreshProfilePicker();applyProfileToForm();save();render();location.hash='titles'};$('#searchBox').addEventListener('input',render);$('#resetBtn').onclick=()=>{$('#searchBox').value='';render()};$('#closeModal').onclick=()=>$('#detailsModal').close();}
function passMovie(m){let q=$('#searchBox').value.trim().toLowerCase();if(activeGenre&&activeGenre!=='All'&&!m.genres.includes(activeGenre))return false;if(q&&!(`${m.title} ${m.year} ${m.genres.join(' ')} ${m.providers.join(' ')}`.toLowerCase().includes(q)))return false;if(profile.genres&&profile.genres.length&&!m.genres.some(g=>profile.genres.includes(g)))return false;if(profile.release&&profile.release!=='any'&&m.months>Number(profile.release))return false;if(profile.fromYear&&m.year<Number(profile.fromYear))return false;if(profile.toYear&&m.year>Number(profile.toYear))return false;if(profile.view&&profile.view!=='all'&&m.view!==profile.view)return false;if(profile.providers&&profile.providers.length&&!profile.providers.includes('All')&&!m.providers.some(p=>profile.providers.includes(p)))return false;return true;}
function render(){renderSummary();renderResults();renderLibrary();}
function renderSummary(){let genres=profile.genres?.length?profile.genres.join(', '):'all genres';let providers=profile.providers?.length?profile.providers.join(', '):'all platforms';$('#profileSummary').innerHTML=profile.userName?`<strong>${profile.profileName||profile.userName}</strong><br>User: ${profile.userName}<br>${genres}<br>${providers}`:'No profile saved yet.';$('#libraryCount').textContent=library.size;}
function renderResults(){renderGenreRail();let list=MOVIES.filter(passMovie);$('#results').innerHTML=list.map(m=>card(m)).join('');$('#emptyState').classList.toggle('hidden',list.length>0);$$('[data-save]').forEach(b=>b.onclick=()=>{library.add(b.dataset.save);save();renderLibrary();renderSummary();renderV5Drawer();});$$('[data-details]').forEach(b=>b.onclick=()=>showDetails(MOVIES.find(m=>m.id===b.dataset.details)));renderV5Drawer();}
function card(m){let saved=library.has(m.id);return `<article class="movie-card" style="--c1:${m.c1};--c2:${m.c2}" draggable="true" ondragstart="event.dataTransfer.setData('text/plain','${m.id}')"><div class="poster-glow"></div><p class="eyebrow">${m.year} · ${m.view}</p><h3>${m.title}</h3><div class="chips">${m.genres.map(g=>`<span class="chip">${g}</span>`).join('')}${m.providers.map(p=>`<span class="chip">${p}</span>`).join('')}</div><p>${m.synopsis}</p><div class="card-actions"><a target="_blank" rel="noopener" href="${m.trailer}">Trailer</a><a target="_blank" rel="noopener" href="${imdbUrl(m)}">IMDb</a><button data-details="${m.id}" type="button">Availability</button><button class="save" data-save="${m.id}" type="button">${saved?'Saved':'Save trailer'}</button></div></article>`}
function showDetails(m){let tribute='https://www.google.com/search?q=Tribute+Now+Playing+'+encodeURIComponent(profile.zip||'near me');let providers=m.providers.map(p=>p==='In theaters'?`<a target="_blank" rel="noopener" href="${tribute}">In theaters — open Tribute / Now Playing</a>`:`<a target="_blank" rel="noopener" href="https://www.google.com/search?q=${encodeURIComponent(m.title+' '+p)}">${p}</a>`).join('');$('#modalBody').innerHTML=`<p class="eyebrow">Availability</p><h2>${m.title}</h2><p>${m.synopsis}</p><div class="route-list">${providers}<a target="_blank" rel="noopener" href="${imdbUrl(m)}">IMDb title page search</a></div>`;$('#detailsModal').showModal();}
function renderLibrary(){let saved=[...library].map(id=>MOVIES.find(m=>m.id===id)).filter(Boolean).sort((a,b)=>b.year-a.year||a.title.localeCompare(b.title));let trailers=$('#trailerLibrary'), titles=$('#titleLibrary');trailers.ondragover=e=>{e.preventDefault();trailers.classList.add('drop-ready')};trailers.ondragleave=()=>trailers.classList.remove('drop-ready');trailers.ondrop=e=>{e.preventDefault();trailers.classList.remove('drop-ready');let id=e.dataTransfer.getData('text/plain');if(id){library.add(id);save();render();}};trailers.innerHTML=saved.length?saved.map(m=>`<div class="library-item"><strong>${m.title}</strong><span class="muted">Trailer of interest · ${m.providers.join(', ')}</span><div class="library-actions"><a target="_blank" rel="noopener" href="${m.trailer}">Rewatch trailer</a><a target="_blank" rel="noopener" href="${imdbUrl(m)}">IMDb</a><button data-remove="${m.id}" type="button">Remove</button></div></div>`).join(''):'<p class="muted">Save trailers from any point in the long list. In v5 the sticky drawer stays available while you scroll.</p>';titles.innerHTML=saved.length?saved.map(m=>`<div class="library-item"><strong>${m.title}</strong><span class="muted">Saved title · ${m.genres.join(', ')}</span><div class="library-actions"><button data-remove="${m.id}" type="button">Remove</button></div></div>`).join(''):'<p class="muted">Saved titles will appear here.</p>';$$('[data-remove]').forEach(b=>b.onclick=()=>{library.delete(b.dataset.remove);save();render();});renderV5Drawer();}
function renderGenreRail(){let host=document.getElementById('v5GenreRail');if(!host){let section=document.getElementById('titles');if(!section)return;host=document.createElement('div');host.id='v5GenreRail';host.className='v5-genre-rail';section.insertBefore(host,section.querySelector('.results-grid')||section.firstChild);}let choices=genreChoices();if(!choices.includes(activeGenre))activeGenre='All';host.innerHTML='<strong>Genre filter</strong>'+choices.map(g=>`<button type="button" class="${g===activeGenre?'active':''}" data-genre="${g}">${g}</button>`).join('');host.querySelectorAll('[data-genre]').forEach(b=>b.onclick=()=>setActiveGenre(b.dataset.genre));}
function renderV5Drawer(){let drawer=document.getElementById('v5Drawer')||document.getElementById('v5StickyDrawer');if(!drawer){drawer=document.createElement('aside');drawer.id='v5Drawer';drawer.className='v5-drawer';drawer.setAttribute('aria-label','Trailers of Interest saved drawer');drawer.innerHTML='<button class="v5-drawer-tab" type="button" aria-expanded="true" aria-controls="v5DrawerPanel">Trailers of Interest</button><div id="v5DrawerPanel" class="v5-drawer-panel"></div>';document.body.appendChild(drawer);drawer.querySelector('.v5-drawer-tab').onclick=()=>{drawer.classList.toggle('collapsed');drawer.querySelector('.v5-drawer-tab').setAttribute('aria-expanded',String(!drawer.classList.contains('collapsed')))}}let panel=drawer.querySelector('.v5-drawer-panel');drawer.ondragover=e=>{e.preventDefault();drawer.classList.add('drop-ready')};drawer.ondragleave=()=>drawer.classList.remove('drop-ready');drawer.ondrop=e=>{e.preventDefault();drawer.classList.remove('drop-ready');let id=e.dataTransfer.getData('text/plain');if(id){library.add(id);save();render();}};let saved=[...library].map(id=>MOVIES.find(m=>m.id===id)).filter(Boolean);let list=saved.length?saved.map(m=>'<div><strong>'+m.title+'</strong><button data-remove="'+m.id+'" type="button">Remove</button></div>').join(''):'<em>No trailers saved yet.</em>';panel.innerHTML='<p class="eyebrow">Sticky drawer</p><p class="muted">Drop or save trailers here without scrolling back.</p><div class="v5-drawer-list">'+list+'</div><button id="v5ShareList" type="button">Copy share list</button>';panel.querySelectorAll('[data-remove]').forEach(b=>b.onclick=()=>{library.delete(b.dataset.remove);save();render();});let share=panel.querySelector('#v5ShareList');if(share)share.setAttribute('aria-live','polite');if(share)share.onclick=async()=>{let text=saved.map(m=>`${m.title} (${m.year}) - ${imdbUrl(m)}`).join('\\n')||'No saved trailers yet.';try{await navigator.clipboard.writeText(text);share.textContent='Copied list';}catch(e){share.textContent='Share list ready';}}}
function render(){renderSummary();renderResults();renderLibrary();}
window.archiveTitle=id=>{library.delete(id);save();render()};
init();