const GENRES = ['Old','Rom Com','Drama','Comedy','Horror','Sci Fi','Western','Faith / Inspiration','Children','Documentary','Anime','Adventure','Crime','Fantasy','History','Music','Mystery','Thriller','War'];
const THEATERS = ['AMC','Regal','Alamo','Phoenix','All theaters'];
const STREAMERS = ['Netflix','Prime Video','Disney+','Apple TV / iTunes','Angel','Max','Hulu','Peacock','Paramount+'];
const MOVIES = [
  {id:'dune-2', title:'Dune: Part Two', year:2024, ageMonths:4, runtime:166, score:95, list:['popular','top','theaters'], route:'theater', genre:['Sci Fi','Adventure'], mood:['spectacle','serious'], view:'sponsored', providers:['AMC','Regal','Alamo','Apple TV / iTunes'], availability:{AMC:'Showtimes',Regal:'Showtimes',Alamo:'Showtimes','Apple TV / iTunes':'Rent later'}, color:['#b45309','#111827'], synopsis:'A big-screen spectacle for people who want the theater to feel worth it.'},
  {id:'inside-out-2', title:'Inside Out 2', year:2024, ageMonths:2, runtime:96, score:91, list:['popular','theaters','family','under2'], route:'theater', genre:['Children','Comedy'], mood:['family','funny'], view:'sponsored', providers:['AMC','Regal','Disney+'], availability:{AMC:'Showtimes',Regal:'Showtimes','Disney+':'Streaming later'}, color:['#e879f9','#22d3ee'], synopsis:'A family-safe pick with a fast trailer-first decision path.'},
  {id:'past-lives', title:'Past Lives', year:2023, ageMonths:12, runtime:106, score:94, list:['top','streaming','under2'], route:'streaming', genre:['Drama','Rom Com'], mood:['quiet','award'], view:'ad-free', providers:['Netflix','Apple TV / iTunes'], availability:{Netflix:'Streaming','Apple TV / iTunes':'Rent / Buy'}, color:['#0f766e','#1e293b'], synopsis:'A slower adult drama where mood matching matters more than popularity.'},
  {id:'oppenheimer', title:'Oppenheimer', year:2023, ageMonths:11, runtime:180, score:93, list:['top','popular','streaming'], route:'streaming', genre:['Drama','History'], mood:['serious','award'], view:'vod', providers:['Prime Video','Apple TV / iTunes'], availability:{'Prime Video':'Streaming','Apple TV / iTunes':'Rent / Buy'}, color:['#7f1d1d','#111827'], synopsis:'For users asking for prestige, awards, and a long-form night.'},
  {id:'casablanca', title:'Casablanca', year:1942, ageMonths:999, runtime:102, score:99, list:['top','classics','under2'], route:'rent-buy', genre:['Old','Rom Com'], mood:['classic','timeless'], view:'ad-free', providers:['Apple TV / iTunes','Prime Video'], availability:{'Apple TV / iTunes':'Rent / Buy','Prime Video':'Rent / Buy'}, color:['#334155','#020617'], synopsis:'A clean example of classic-library discovery without TV clutter.'},
  {id:'civil-war', title:'Civil War', year:2024, ageMonths:5, runtime:109, score:82, list:['popular','theaters','under2'], route:'theater', genre:['Thriller','Drama'], mood:['intense','serious'], view:'sponsored', providers:['AMC','Regal','Apple TV / iTunes'], availability:{AMC:'Showtimes',Regal:'Showtimes','Apple TV / iTunes':'Rent later'}, color:['#78350f','#0f172a'], synopsis:'Current-release routing where users need theater versus later-home clarity.'},
  {id:'the-holdovers', title:'The Holdovers', year:2023, ageMonths:9, runtime:133, score:92, list:['top','streaming'], route:'streaming', genre:['Comedy','Drama'], mood:['warm','award'], view:'vod', providers:['Prime Video','Apple TV / iTunes'], availability:{'Prime Video':'Streaming','Apple TV / iTunes':'Rent / Buy'}, color:['#365314','#111827'], synopsis:'A profile-friendly recommendation for warm, character-driven movie nights.'},
  {id:'barbie', title:'Barbie', year:2023, ageMonths:11, runtime:114, score:88, list:['popular','streaming','under2'], route:'streaming', genre:['Comedy','Fantasy'], mood:['bright','funny'], view:'sponsored', providers:['Max','Apple TV / iTunes'], availability:{Max:'Streaming','Apple TV / iTunes':'Rent / Buy'}, color:['#be185d','#f9a8d4'], synopsis:'Popular and social, but still needs provider clarity before a user commits.'},
  {id:'anora', title:'Anora', year:2024, ageMonths:1, runtime:139, score:90, list:['top','theaters'], route:'theater', genre:['Drama','Comedy'], mood:['award','adult'], view:'ad-free', providers:['Alamo','AMC'], availability:{Alamo:'Limited showtimes',AMC:'Limited showtimes'}, color:['#9f1239','#312e81'], synopsis:'A smaller theatrical title where discovery and local route clarity matter.'},
  {id:'mi-fallout', title:'Mission: Impossible — Fallout', year:2018, ageMonths:80, runtime:147, score:89, list:['popular','streaming'], route:'streaming', genre:['Adventure','Thriller'], mood:['action','spectacle'], view:'vod', providers:['Prime Video','Paramount+','Apple TV / iTunes'], availability:{'Prime Video':'Streaming','Paramount+':'Streaming','Apple TV / iTunes':'Rent / Buy'}, color:['#1d4ed8','#020617'], synopsis:'A high-confidence action fallback for users who want energy.'},
  {id:'paddington-2', title:'Paddington 2', year:2017, ageMonths:90, runtime:103, score:98, list:['top','family','under2'], route:'rent-buy', genre:['Children','Comedy'], mood:['family','warm','funny'], view:'ad-free', providers:['Apple TV / iTunes','Prime Video'], availability:{'Apple TV / iTunes':'Rent / Buy','Prime Video':'Rent / Buy'}, color:['#dc2626','#1d4ed8'], synopsis:'A safe, joyful family pick when the profile says no risk tonight.'},
  {id:'godfather', title:'The Godfather', year:1972, ageMonths:999, runtime:175, score:98, list:['top','classics'], route:'streaming', genre:['Old','Crime'], mood:['classic','serious'], view:'ad-free', providers:['Prime Video','Paramount+','Apple TV / iTunes'], availability:{'Prime Video':'Streaming','Paramount+':'Streaming','Apple TV / iTunes':'Rent / Buy'}, color:['#111827','#7f1d1d'], synopsis:'A canonical classic for users who want prestige and old-school weight.'}
];
const els = {};
let state = {
  list:'all', query:'', route:'all', provider:'selected', mood:'all', runtime:'all', release:'any', fromYear:'', toYear:'', viewType:'all', zip:'',
  genres:new Set(JSON.parse(localStorage.getItem('mmeGenres') || '[]')),
  platforms:new Set(JSON.parse(localStorage.getItem('mmePlatforms') || JSON.stringify(['AMC','Regal','Alamo','Netflix','Prime Video','Apple TV / iTunes']))),
  saved:new Set(JSON.parse(localStorage.getItem('appleBaselineSaved') || '[]')),
  hidden:new Set(JSON.parse(localStorage.getItem('appleBaselineHidden') || '[]')),
  seen:new Set(JSON.parse(sessionStorage.getItem('appleBaselineSeen') || '[]')),
  metrics: JSON.parse(sessionStorage.getItem('appleBaselineMetrics') || '{"views":0,"trailers":0,"routes":0,"notForMe":0}')
};
function $(id){return document.getElementById(id)}
function bind(id,event,handler){ const el=$(id); if(el) el.addEventListener(event,handler); else console.warn('missing control',id); return el; }
function init(){
  ['movieGrid','movieTemplate','resultCount','activeSummary','detailsDialog','dialogBody','metricViews','metricTrailers','metricSaves','metricRoutes','emptyState','libraryBody'].forEach(id=>els[id]=$(id));
  renderChecks(); renderProviderFilter(); bindControls(); loadStoredProfileToInputs(); render(); renderLibrary();
}
function bindControls(){
  document.querySelectorAll('[data-list]').forEach(btn=>btn.addEventListener('click',()=>setList(btn.dataset.list)));
  bind('searchInput','input',e=>{state.query=e.target.value; render();});
  bind('routeFilter','change',e=>{state.route=e.target.value; render();});
  bind('providerFilter','change',e=>{state.provider=e.target.value; render();});
  bind('moodFilter','change',e=>{state.mood=e.target.value; render();});
  bind('runtimeFilter','change',e=>{state.runtime=e.target.value; render();});
  bind('zipInput','input',e=>{state.zip=e.target.value.trim(); persist();});
  document.querySelectorAll('input[name=releaseRange]').forEach(r=>r.addEventListener('change',e=>{state.release=e.target.value; render();}));
  document.querySelectorAll('input[name=viewType]').forEach(r=>r.addEventListener('change',e=>{state.viewType=e.target.value; render();}));
  bind('fromYearInput','input',e=>{state.fromYear=e.target.value.trim(); render();});
  bind('toYearInput','input',e=>{state.toYear=e.target.value.trim(); render();});
  bind('resetBtn','click',resetFilters); bind('emptyResetBtn','click',resetFilters); bind('loadDemoBtn','click',loadDemoProfile);
  bind('saveProfileBtn','click',saveProfile); bind('exportBtn','click',exportSession); bind('libraryTopBtn','click',()=>location.hash='library');
  bind('clearLibraryBtn','click',()=>{state.saved.clear(); persist(); render(); renderLibrary();});
  bind('selectAllPlatformsBtn','click',()=>{THEATERS.concat(STREAMERS).forEach(p=>state.platforms.add(p)); renderChecks(); renderProviderFilter(); render();});
  const lib=$('library'); if(lib){ lib.addEventListener('dragover',e=>{e.preventDefault(); lib.classList.add('drag-over');}); lib.addEventListener('dragleave',()=>lib.classList.remove('drag-over')); lib.addEventListener('drop',e=>{e.preventDefault(); lib.classList.remove('drag-over'); const id=e.dataTransfer.getData('text/plain'); if(id) saveMovie(id);}); }
  bind('closeDialog','click',()=>els.detailsDialog.close());
}
function renderChecks(){
  $('genreList').innerHTML=GENRES.map(g=>`<label><input type="checkbox" data-genre="${escapeHtml(g)}" ${state.genres.has(g)?'checked':''}/> ${escapeHtml(g)}</label>`).join('');
  $('genreList').querySelectorAll('input').forEach(i=>i.addEventListener('change',e=>{e.target.checked?state.genres.add(e.target.dataset.genre):state.genres.delete(e.target.dataset.genre); persist(); render();}));
  $('theaterList').innerHTML=THEATERS.map(p=>`<label><input type="checkbox" data-platform="${escapeHtml(p)}" ${state.platforms.has(p)?'checked':''}/> ${escapeHtml(p)}</label>`).join('');
  $('streamingList').innerHTML=STREAMERS.map(p=>`<label><input type="checkbox" data-platform="${escapeHtml(p)}" ${state.platforms.has(p)?'checked':''}/> ${escapeHtml(p)}</label>`).join('');
  document.querySelectorAll('[data-platform]').forEach(i=>i.addEventListener('change',e=>{e.target.checked?state.platforms.add(e.target.dataset.platform):state.platforms.delete(e.target.dataset.platform); persist(); renderProviderFilter(); render();}));
}
function renderProviderFilter(){
  const select=$('providerFilter'); if(!select) return; const current=select.value||'selected'; const opts=['<option value="selected">Selected platforms</option>','<option value="all">Any provider</option>'].concat([...new Set(THEATERS.concat(STREAMERS))].map(p=>`<option value="${escapeHtml(p)}">${escapeHtml(p)}</option>`));
  select.innerHTML=opts.join(''); select.value=[...select.options].some(o=>o.value===current)?current:'selected'; state.provider=select.value;
}
function persist(){
  localStorage.setItem('mmeGenres', JSON.stringify([...state.genres])); localStorage.setItem('mmePlatforms', JSON.stringify([...state.platforms])); localStorage.setItem('mmeZip', state.zip);
  localStorage.setItem('appleBaselineSaved', JSON.stringify([...state.saved])); localStorage.setItem('appleBaselineHidden', JSON.stringify([...state.hidden]));
  sessionStorage.setItem('appleBaselineSeen', JSON.stringify([...state.seen])); sessionStorage.setItem('appleBaselineMetrics', JSON.stringify(state.metrics));
}
function setList(list){ state.list=list; document.querySelectorAll('[data-list]').forEach(b=>b.classList.toggle('active',b.dataset.list===list)); render(); }
function selectedPlatformMatch(movie){ if(state.provider==='all') return true; if(state.provider && state.provider!=='selected') return movie.providers.includes(state.provider); if(!state.platforms.size) return true; return movie.providers.some(p=>state.platforms.has(p) || (state.platforms.has('All theaters') && THEATERS.includes(p))); }
function matches(movie){
  const q=state.query.trim().toLowerCase(); if(state.hidden.has(movie.id)) return false; if(state.list!=='all'&&!movie.list.includes(state.list)) return false; if(state.route!=='all'&&movie.route!==state.route) return false; if(!selectedPlatformMatch(movie)) return false;
  if(state.mood!=='all'&&!movie.mood.includes(state.mood)) return false; if(state.runtime==='under120'&&movie.runtime>=120) return false; if(state.runtime==='over120'&&movie.runtime<120) return false; if(state.viewType!=='all'&&movie.view!==state.viewType) return false;
  if(state.genres.size && !movie.genre.some(g=>state.genres.has(g))) return false; if(state.release!=='any' && movie.ageMonths>Number(state.release)) return false; const fy=Number(state.fromYear), ty=Number(state.toYear); if(fy&&movie.year<fy) return false; if(ty&&movie.year>ty) return false;
  if(q){ const hay=[movie.title,movie.year,movie.runtime,movie.route,...movie.genre,...movie.mood,...movie.providers,movie.synopsis].join(' ').toLowerCase(); if(!hay.includes(q)) return false; }
  return true;
}
function filteredMovies(){ return MOVIES.filter(matches).sort((a,b)=>b.score-a.score || a.runtime-b.runtime); }
function routeLabel(route){return route==='theater'?'In theaters':route==='streaming'?'Streaming':'Rent / Buy'}
function providerClass(label){const l=label.toLowerCase(); if(l.includes('showtime'))return 'theater'; if(l.includes('stream'))return 'available'; return 'paid'}
function render(){
  const movies=filteredMovies(); els.movieGrid.innerHTML=''; els.emptyState.hidden=movies.length!==0; for(const m of movies){ if(!state.seen.has(m.id)) state.seen.add(m.id); } state.metrics.views=state.seen.size;
  for(const movie of movies){
    const node=els.movieTemplate.content.firstElementChild.cloneNode(true); node.dataset.id=movie.id; node.querySelector('.poster').style.setProperty('--posterA',movie.color[0]); node.querySelector('.poster').style.setProperty('--posterB',movie.color[1]); node.querySelector('.poster span').textContent=movie.title.split(/\s+/).slice(0,2).map(w=>w[0]).join('');
    node.querySelector('.card-kicker').textContent=`${routeLabel(movie.route)} • ${movie.runtime} min • ${movie.score}% fit`; node.querySelector('h3').textContent=`${movie.title} (${movie.year})`; node.querySelector('.synopsis').textContent=movie.synopsis;
    node.querySelector('.badges').innerHTML=movie.genre.concat(movie.mood.slice(0,2)).map(x=>`<span class="badge">${escapeHtml(x)}</span>`).join('');
    node.querySelector('.availability').innerHTML=Object.entries(movie.availability).map(([k,v])=>`<span class="provider ${providerClass(v)} ${platformIsSelected(k)?'':'dim'}">${escapeHtml(k)}: ${escapeHtml(v)}</span>`).join('');
    node.querySelector('.trailer-btn').addEventListener('click',()=>openTrailer(movie)); node.querySelector('.details-btn').addEventListener('click',()=>openDetails(movie)); node.querySelector('.imdb-btn').addEventListener('click',()=>openIMDb(movie)); node.querySelector('.not-btn').addEventListener('click',()=>hideMovie(movie.id));
    const save=node.querySelector('.save-btn'); save.textContent=state.saved.has(movie.id)?'★':'☆'; save.addEventListener('click',()=>saveMovie(movie.id)); node.addEventListener('dragstart',e=>{node.classList.add('dragging'); e.dataTransfer.setData('text/plain',movie.id);}); node.addEventListener('dragend',()=>node.classList.remove('dragging'));
    els.movieGrid.appendChild(node);
  }
  els.resultCount.textContent=`${movies.length} match${movies.length===1?'':'es'}`; els.activeSummary.textContent=summaryText(); updateMetrics(); persist(); renderLibrary();
}
function platformIsSelected(p){return state.provider==='all'||state.provider===p||state.platforms.has(p)||(state.platforms.has('All theaters')&&THEATERS.includes(p));}
function summaryText(){return [state.list!=='all'?state.list:'all lists',state.genres.size?`${state.genres.size} genres`:'any genre',state.release!=='any'?`past ${state.release} months`:'any date',state.provider==='selected'?'selected platforms':state.provider].join(' • ');}
function updateMetrics(){els.metricViews.textContent=state.metrics.views; els.metricTrailers.textContent=state.metrics.trailers; els.metricRoutes.textContent=state.metrics.routes; els.metricSaves.textContent=state.saved.size;}
function saveMovie(id){ if(state.saved.has(id)) state.saved.delete(id); else state.saved.add(id); render(); }
function hideMovie(id){state.hidden.add(id); state.saved.delete(id); state.metrics.notForMe=(state.metrics.notForMe||0)+1; render();}
function renderLibrary(){ const movies=MOVIES.filter(m=>state.saved.has(m.id)); els.libraryBody.innerHTML=movies.length?movies.map(m=>`<article class="library-item"><b>${escapeHtml(m.title)}</b><span>${escapeHtml(routeLabel(m.route))} • ${m.runtime} min • ${m.score}% fit</span><div class="route-actions"><button class="secondary" onclick="openDetailsById('${m.id}')">Route</button><button class="secondary" onclick="openTrailerById('${m.id}')">Trailer</button></div></article>`).join(''):'<p class="empty-state">No saved trailers yet. Drag a title card here or tap Save.</p>'; }
function openTrailer(movie){state.metrics.trailers+=1; updateMetrics(); persist(); window.open(`https://www.youtube.com/results?search_query=${encodeURIComponent(movie.title+' official trailer')}`,'_blank','noopener,noreferrer'); openDetails(movie,'Trailer opened');}
function openTrailerById(id){const m=MOVIES.find(x=>x.id===id); if(m) openTrailer(m);}
function openIMDb(movie){window.open(`https://www.imdb.com/find/?q=${encodeURIComponent(movie.title)}`,'_blank','noopener,noreferrer');}
function openDetailsById(id){const m=MOVIES.find(x=>x.id===id); if(m) openDetails(m);}
function openDetails(movie,eyebrow='Where to watch'){state.metrics.routes+=1; updateMetrics(); persist(); const zip=state.zip||localStorage.getItem('mmeZip')||''; const routes=Object.entries(movie.availability).map(([k,v])=>`<div class="route-row"><b>${escapeHtml(k)}</b><span>${escapeHtml(v)}</span></div>`).join(''); els.dialogBody.innerHTML=`<p class="eyebrow">${escapeHtml(eyebrow)}</p><h2>${escapeHtml(movie.title)}</h2><p class="synopsis">${escapeHtml(movie.synopsis)}</p><div class="badges">${movie.genre.concat(movie.mood).map(x=>`<span class="badge">${escapeHtml(x)}</span>`).join('')}</div><div class="route-list">${routes}</div><div class="route-actions"><a class="primary" target="_blank" rel="noopener" href="https://www.tribute.ca/showtimes/?q=${encodeURIComponent(movie.title)}&postal=${encodeURIComponent(zip)}">Tribute showtimes</a><a class="secondary" target="_blank" rel="noopener" href="https://www.imdb.com/find/?q=${encodeURIComponent(movie.title)}">IMDb title page</a><button class="secondary" onclick="openTrailerById('${movie.id}')">Trailer platform</button><button class="secondary" onclick="saveMovie('${movie.id}')">${state.saved.has(movie.id)?'Remove from library':'Save to library'}</button></div><p class="fineprint">Demo route: selected theater/streaming platform availability is shown above. Production needs live provider contracts and showtime APIs.</p>`; els.detailsDialog.showModal();}
function resetFilters(){state.list='all'; state.query=''; state.route='all'; state.provider='selected'; state.mood='all'; state.runtime='all'; state.release='any'; state.fromYear=''; state.toYear=''; state.viewType='all'; state.hidden.clear(); if($('searchInput')) $('searchInput').value=''; if($('routeFilter')) $('routeFilter').value='all'; if($('providerFilter')) $('providerFilter').value='selected'; if($('moodFilter')) $('moodFilter').value='all'; if($('runtimeFilter')) $('runtimeFilter').value='all'; if($('fromYearInput')) $('fromYearInput').value=''; if($('toYearInput')) $('toYearInput').value=''; document.querySelector('input[name=releaseRange][value=any]').checked=true; document.querySelector('input[name=viewType][value=all]').checked=true; setList('all');}
function loadDemoProfile(){state.genres=new Set(['Old','Crime','Drama','Comedy']); state.platforms=new Set(['AMC','Regal','Alamo','Netflix','Prime Video','Apple TV / iTunes']); state.zip='20001'; $('zipInput').value=state.zip; renderChecks(); renderProviderFilter(); persist(); render(); location.hash='titles';}
function loadStoredProfileToInputs(){ const zipEl=$('zipInput'); if(zipEl){ zipEl.value=localStorage.getItem('mmeZip')||''; state.zip=zipEl.value; } const profile=JSON.parse(localStorage.getItem('mmeActiveProfile')||'{}'); if(profile.userName && $('userNameInput')) $('userNameInput').value=profile.userName; if(profile.passcode && $('passcodeInput')) $('passcodeInput').value=profile.passcode; }
function saveProfile(){ const profile={userName:$('userNameInput').value.trim(), passcode:$('passcodeInput').value, genres:[...state.genres], platforms:[...state.platforms], zip:state.zip, savedAt:new Date().toISOString()}; localStorage.setItem('mmeActiveProfile',JSON.stringify(profile)); persist(); const status=$('profileStatus'); if(status) status.textContent='Demo profile saved locally.'; }
function exportSession(){ const payload={prototype:'moviesmadeeasy-sketch-flow-mvp',exportedAt:new Date().toISOString(),profile:JSON.parse(localStorage.getItem('mmeActiveProfile')||'{}'),filters:{list:state.list,query:state.query,route:state.route,provider:state.provider,mood:state.mood,runtime:state.runtime,release:state.release,fromYear:state.fromYear,toYear:state.toYear,viewType:state.viewType,genres:[...state.genres],platforms:[...state.platforms],zip:state.zip},metrics:{...state.metrics,saves:state.saved.size,hidden:state.hidden.size},library:[...state.saved].map(id=>MOVIES.find(m=>m.id===id)).filter(Boolean).map(m=>({id:m.id,title:m.title,route:m.route,providers:m.providers,score:m.score})),hiddenMovies:[...state.hidden].map(id=>MOVIES.find(m=>m.id===id)).filter(Boolean).map(m=>({id:m.id,title:m.title})),visibleMovies:filteredMovies().map(m=>({id:m.id,title:m.title,route:m.route,score:m.score}))}; const blob=new Blob([JSON.stringify(payload,null,2)],{type:'application/json'}); const a=document.createElement('a'); a.href=URL.createObjectURL(blob); a.download=`moviesmadeeasy-sketch-flow-session-${new Date().toISOString().replace(/[:.]/g,'-')}.json`; document.body.appendChild(a); a.click(); a.remove(); URL.revokeObjectURL(a.href);}
function escapeHtml(value){return String(value).replace(/[&<>'"]/g,ch=>({'&':'&amp;','<':'&lt;','>':'&gt;',"'":'&#39;','"':'&quot;'}[ch]));}
window.openDetailsById=openDetailsById; window.openTrailerById=openTrailerById; window.saveMovie=saveMovie; window.hideMovie=hideMovie; document.addEventListener('DOMContentLoaded',init);
